name: management-system-pro-umi

on:
  push:
    branches: [ umi ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # https://stackoverflow.com/questions/71464006/error-an-unexpected-error-occurred-eacces-permission-denied-in-github-actions
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install yarn -g
      - name: Build React App
        run: | 
          yarn
          yarn global add umi@3.5.0
          umi build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKER_REPO_USER_NAME }}
          password: ${{ secrets.ALIYUN_DOCKER_REPO_USER_PASSWORD }}

      - name: Build image push to aliyun
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/reddwarf-pro/react-admin-new:${{ github.sha }} 
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          push: true
    
       # https://github.com/steebchen/kubectl
      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image --record deployment/react-admin-new react-admin-new=registry.cn-hongkong.aliyuncs.com/reddwarf-pro/react-admin-new:${{ github.sha }} -n reddwarf-pro

      - name: verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.21.0 # specify kubectl binary version explicitly
          command: rollout status deployment/react-admin-new -n reddwarf-pro
